server:
  port: 8080

spring:
  application:
    name: customer-api
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    mongodb:
      uri: mongodb://db-mongo:27017/customersdb
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui-custom.html
  version: 1.0.0
