server:
  port: 8080

spring:
  application:
    name: customer-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/customersdb
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
